In [1]:
import pandas as pd

In [2]:
dfMovies = pd.read_csv('movies.csv')
dfMovies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller
10,11,"American President, The (1995)",Comedy|Drama|Romance
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror
12,13,Balto (1995),Adventure|Animation|Children
13,14,Nixon (1995),Drama
14,15,Cutthroat Island (1995),Action|Adventure|Romance
15,16,Casino (1995),Crime|Drama
16,17,Sense and Sensibility (1995),Drama|Romance
17,18,Four Rooms (1995),Comedy
18,19,Ace Ventura: When Nature Calls (1995),Comedy
19,20,Money Train (1995),Action|Comedy|Crime|Drama|Thriller
20,21,Get Shorty (1995),Comedy|Crime|Thriller
21,22,Copycat (1995),Crime|Drama|Horror|Mystery|Thriller
22,23,Assassins (1995),Action|Crime|Thriller
23,24,Powder (1995),Drama|Sci-Fi
24,25,Leaving Las Vegas (1995),Drama|Romance
25,26,Othello (1995),Drama
26,27,Now and Then (1995),Children|Drama
27,28,Persuasion (1995),Drama|Romance
28,29,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi
29,30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Crime|Drama
...,...,...,...
27248,131146,Werner - Volles Rooäää (1999),Animation|Comedy
27249,131148,What A Man (2011),Comedy|Romance
27250,131150,7 Dwarves: The Forest Is Not Enough (2006),Comedy
27251,131152,The Fat Spy (1966),Comedy
27252,131154,"Die Bademeister – Weiber, saufen, Leben retten...",Comedy
27253,131156,Ants in the Pants 2 (2002),Comedy
27254,131158,"Manta, Manta (1991)",Comedy
27255,131160,Oscar and the Lady in Pink (2009),Drama
27256,131162,Por un puñado de besos (2014),Drama|Romance
27257,131164,Vietnam in HD (2011),War
27258,131166,WWII IN HD (2009),(no genres listed)
27259,131168,Phoenix (2014),Drama
27260,131170,Parallels (2015),Sci-Fi
27261,131172,Closed Curtain (2013),(no genres listed)
27262,131174,Gentlemen (2014),Drama|Romance|Thriller
27263,131176,A Second Chance (2014),Drama
27264,131180,Dead Rising: Watchtower (2015),Action|Horror|Thriller
27265,131231,Standby (2014),Comedy|Romance
27266,131237,What Men Talk About (2010),Comedy
27267,131239,Three Quarter Moon (2011),Comedy|Drama
27268,131241,Ants in the Pants (2000),Comedy|Romance
27269,131243,Werner - Gekotzt wird später (2003),Animation|Comedy
27270,131248,Brother Bear 2 (2006),Adventure|Animation|Children|Comedy|Fantasy
27271,131250,No More School (2000),Comedy
27272,131252,Forklift Driver Klaus: The First Day on the Jo...,Comedy|Horror
27273,131254,Kein Bund für's Leben (2007),Comedy
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy
27275,131258,The Pirates (2014),Adventure
27276,131260,Rentun Ruusu (2001),(no genres listed)
27277,131262,Innocence (2014),Adventure|Fantasy|Horror

In [3]:
dfTags = pd.read_csv('tags.csv')
dfTags

,userId,movieId,tag,timestamp
0,18,4141,Mark Waters,1240597180
1,65,208,dark hero,1368150078
2,65,353,dark hero,1368150079
3,65,521,noir thriller,1368149983
4,65,592,dark hero,1368150078
5,65,668,bollywood,1368149876
6,65,898,screwball comedy,1368150160
7,65,1248,noir thriller,1368149983
8,65,1391,mars,1368150055
9,65,1617,neo-noir,1368150217
10,65,1694,jesus,1368149925
11,65,1783,noir thriller,1368149983
12,65,2022,jesus,1368149925
13,65,2193,dragon,1368151314
14,65,2353,conspiracy theory,1368151266
15,65,2662,mars,1368150055
16,65,2726,noir thriller,1368149983
17,65,2840,jesus,1368149925
18,65,3052,jesus,1368149926
19,65,5135,bollywood,1368149876
20,65,6539,treasure,1368149949
21,65,6874,dark hero,1368150079
22,65,7013,noir thriller,1368149983
23,65,7318,jesus,1368149925
24,65,8529,stranded,1368150012
25,65,8622,conspiracy theory,1368151266
26,65,27803,Oscar (Best Foreign Language Film),1305008715
27,65,27866,New Zealand,1304957153
28,65,48082,surreal,1304958354
29,65,48082,unusual,1304958359
...,...,...,...,...
465534,138436,81932,big hair,1298754654
465535,138436,81932,Mark Wahlberg,1298754636
465536,138436,81932,pigs,1298754658
465537,138436,81932,prostitution,1298754620
465538,138437,77154,"This movie should have been called ""How Cocain...",1357384633
465539,138446,317,Christmas,1358983914
465540,138446,317,funny,1358983914
465541,138446,317,Judge Reinhold,1358983914
465542,138446,317,Tim Allen,1358983914
465543,138446,317,whiny kid,1358983946
465544,138446,837,family friendly,1358983693
465545,138446,918,halloween scene,1358984062
465546,138446,918,quirky,1358984051
465547,138446,2396,topless scene,1358973995
465548,138446,3086,Christmas,1358983979
465549,138446,3086,classic,1358983979
465550,138446,3086,funny,1358983979
465551,138446,3086,scary,1358984001
465552,138446,3489,Peter Pan,1358983822
465553,138446,3489,soundtrack,1358983822
465554,138446,3489,visually appealing,1358983822
465555,138446,7045,family friendly,1358983660
465556,138446,7045,Scary Movies To See on Halloween,1358983660
465557,138446,7164,Peter Pan,1358983855
465558,138446,7164,visually appealing,1358983855
465559,138446,55999,dragged,1358983772
465560,138446,55999,Jason Bateman,1358983778
465561,138446,55999,quirky,1358983778
465562,138446,55999,sad,1358983772
465563,138472,923,rise to power,1194037967

In [5]:
dfRatings = pd.read_csv('ratings.csv')
dfRatings

        userId  movieId  rating     timestamp
0            1        2     3.5  1.112486e+09
1            1       29     3.5  1.112485e+09
2            1       32     3.5  1.112485e+09
3            1       47     3.5  1.112485e+09
4            1       50     3.5  1.112485e+09
5            1      112     3.5  1.094786e+09
6            1      151     4.0  1.094786e+09
7            1      223     4.0  1.112486e+09
8            1      253     4.0  1.112485e+09
9            1      260     4.0  1.112485e+09
10           1      293     4.0  1.112485e+09
11           1      296     4.0  1.112485e+09
12           1      318     4.0  1.112485e+09
13           1      337     3.5  1.094786e+09
14           1      367     3.5  1.112486e+09
15           1      541     4.0  1.112485e+09
16           1      589     3.5  1.112486e+09
17           1      593     3.5  1.112485e+09
18           1      653     3.0  1.094786e+09
19           1      919     3.5  1.094786e+09
20           1      924     3.5  1.094786e+09
21           1     1009     3.5  1.112486e+09
22           1     1036     4.0  1.112485e+09
23           1     1079     4.0  1.094786e+09
24           1     1080     3.5  1.112485e+09
25           1     1089     3.5  1.112485e+09
26           1     1090     4.0  1.112485e+09
27           1     1097     4.0  1.112486e+09
28           1     1136     3.5  1.112485e+09
29           1     1193     3.5  1.112485e+09
...        ...      ...     ...           ...
279984    1927    79008     5.0  1.302031e+09
279985    1927    79091     3.5  1.304298e+09
279986    1927    79132     4.0  1.302047e+09
279987    1927    80463     3.0  1.302031e+09
279988    1927    81591     3.0  1.302047e+09
279989    1927    81845     2.5  1.302047e+09
279990    1927    81932     3.5  1.302047e+09
279991    1927    82667     2.0  1.326925e+09
279992    1927    84273     4.5  1.302047e+09
279993    1927    85342     3.0  1.326925e+09
279994    1927    85414     3.0  1.368394e+09
279995    1927    86781     4.0  1.326925e+09
279996    1927    88129     3.0  1.317760e+09
279997    1927    89759     4.5  1.326925e+09
279998    1927    89864     4.0  1.365186e+09
279999    1927    99114     3.5  1.366909e+09
280000    1928       10     5.0  8.293989e+08
280001    1928       14     5.0  8.293989e+08
280002    1928       15     4.0  8.293989e+08
280003    1928       19     3.0  8.294003e+08
280004    1928       21     5.0  8.293989e+08
280005    1928       22     3.0  8.294003e+08
280006    1928       23     1.0  8.294003e+08
280007    1928       25     5.0  8.293989e+08
280008    1928       31     3.0  8.294003e+08
280009    1928       32     5.0  8.293989e+08
280010    1928       34     4.0  8.294003e+08
280011    1928       36     5.0  8.293989e+08
280012    1928       39     4.0  8.294003e+08
280013    1928       44     4.0           NaN

[280014 rows x 4 columns]

In [9]:
#Extract the first row from tags and print its type.
dfTags.head(1).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 4 columns):
userId       1 non-null int64
movieId      1 non-null int64
tag          1 non-null object
timestamp    1 non-null int64
dtypes: int64(3), object(1)
memory usage: 112.0+ bytes

In [26]:
#Extract row 0, 11, 2000 from tags DataFrame.
dfTags.iloc[[0]]

      userId  movieId                tag   timestamp
2000     910    68554  conspiracy theory  1368043943

In [27]:
dfTags.iloc[[11]]

    userId  movieId            tag   timestamp
11      65     1783  noir thriller  1368149983

In [28]:
dfTags.iloc[[2000]]

      userId  movieId                tag   timestamp
2000     910    68554  conspiracy theory  1368043943

In [29]:
#Print index, columns of the DataFrame.
dfTags.index

RangeIndex(start=0, stop=465564, step=1)

In [30]:
dfTags.columns

Index(['userId', 'movieId', 'tag', 'timestamp'], dtype='object')

In [81]:
dfRatings = pd.read_csv('ratings.csv')
dfRatings

        userId  movieId  rating     timestamp
0            1        2     3.5  1.112486e+09
1            1       29     3.5  1.112485e+09
2            1       32     3.5  1.112485e+09
3            1       47     3.5  1.112485e+09
4            1       50     3.5  1.112485e+09
5            1      112     3.5  1.094786e+09
6            1      151     4.0  1.094786e+09
7            1      223     4.0  1.112486e+09
8            1      253     4.0  1.112485e+09
9            1      260     4.0  1.112485e+09
10           1      293     4.0  1.112485e+09
11           1      296     4.0  1.112485e+09
12           1      318     4.0  1.112485e+09
13           1      337     3.5  1.094786e+09
14           1      367     3.5  1.112486e+09
15           1      541     4.0  1.112485e+09
16           1      589     3.5  1.112486e+09
17           1      593     3.5  1.112485e+09
18           1      653     3.0  1.094786e+09
19           1      919     3.5  1.094786e+09
20           1      924     3.5  1.094786e+09
21           1     1009     3.5  1.112486e+09
22           1     1036     4.0  1.112485e+09
23           1     1079     4.0  1.094786e+09
24           1     1080     3.5  1.112485e+09
25           1     1089     3.5  1.112485e+09
26           1     1090     4.0  1.112485e+09
27           1     1097     4.0  1.112486e+09
28           1     1136     3.5  1.112485e+09
29           1     1193     3.5  1.112485e+09
...        ...      ...     ...           ...
279984    1927    79008     5.0  1.302031e+09
279985    1927    79091     3.5  1.304298e+09
279986    1927    79132     4.0  1.302047e+09
279987    1927    80463     3.0  1.302031e+09
279988    1927    81591     3.0  1.302047e+09
279989    1927    81845     2.5  1.302047e+09
279990    1927    81932     3.5  1.302047e+09
279991    1927    82667     2.0  1.326925e+09
279992    1927    84273     4.5  1.302047e+09
279993    1927    85342     3.0  1.326925e+09
279994    1927    85414     3.0  1.368394e+09
279995    1927    86781     4.0  1.326925e+09
279996    1927    88129     3.0  1.317760e+09
279997    1927    89759     4.5  1.326925e+09
279998    1927    89864     4.0  1.365186e+09
279999    1927    99114     3.5  1.366909e+09
280000    1928       10     5.0  8.293989e+08
280001    1928       14     5.0  8.293989e+08
280002    1928       15     4.0  8.293989e+08
280003    1928       19     3.0  8.294003e+08
280004    1928       21     5.0  8.293989e+08
280005    1928       22     3.0  8.294003e+08
280006    1928       23     1.0  8.294003e+08
280007    1928       25     5.0  8.293989e+08
280008    1928       31     3.0  8.294003e+08
280009    1928       32     5.0  8.293989e+08
280010    1928       34     4.0  8.294003e+08
280011    1928       36     5.0  8.293989e+08
280012    1928       39     4.0  8.294003e+08
280013    1928       44     4.0           NaN

[280014 rows x 4 columns]

In [33]:
#Calculate descriptive statistics for the 'ratings'column of the
#ratings DataFrame. Verify using describe().
dfRatings['rating'].describe()

count    280014.000000
mean          3.501062
std           1.067911
min           0.500000
25%           3.000000
50%           3.500000
75%           4.000000
max           5.000000
Name: rating, dtype: float64

In [35]:
#Filter out ratings with rating > 5
dfRatings[dfRatings.rating > 5]

Empty DataFrame
Columns: [userId, movieId, rating, timestamp]
Index: []

In [105]:
#Filter out ratings with rating > 4
dfRatings[dfRatings.rating > 4]

        userId  movieId  rating    timestamp
30           1     1196     4.5  1.11248e+09
31           1     1198     4.5  1.11248e+09
131          1     4993     5.0  1.11248e+09
142          1     5952     5.0  1.11248e+09
158          1     7153     5.0  1.11248e+09
170          1     8507     5.0  1.09479e+09
171          1     8636     4.5  1.11249e+09
176          2       62     5.0  9.74821e+08
177          2       70     5.0  9.74821e+08
180          2      260     5.0  9.74821e+08
181          2      266     5.0  9.74821e+08
183          2      480     5.0  9.74821e+08
184          2      541     5.0  9.74821e+08
185          2      589     5.0  9.74821e+08
188          2      924     5.0  9.74821e+08
190          2     1196     5.0  9.74821e+08
191          2     1210     5.0  9.74821e+08
192          2     1214     5.0  9.74821e+08
193          2     1249     5.0  9.74821e+08
194          2     1259     5.0  9.74821e+08
195          2     1270     5.0  9.74821e+08
196          2     1327     5.0  9.74821e+08
197          2     1356     5.0  9.74821e+08
198          2     1544     5.0  9.74821e+08
201          2     1748     5.0  9.74821e+08
208          2     1974     5.0  9.74821e+08
215          2     2948     5.0  9.74821e+08
220          2     3450     5.0  9.74821e+08
221          2     3513     5.0  9.74821e+08
231          2     3927     5.0  9.74821e+08
...        ...      ...     ...          ...
279849    1927     1080     4.5  1.30205e+09
279855    1927     1206     5.0  1.30205e+09
279866    1927     1732     5.0  1.30205e+09
279867    1927     1884     4.5  1.30205e+09
279872    1927     2329     5.0  1.30205e+09
279878    1927     2959     5.0  1.30205e+09
279883    1927     3476     4.5  1.32113e+09
279897    1927     5218     4.5  1.30217e+09
279901    1927     5618     5.0  1.30205e+09
279908    1927     6016     4.5  1.30205e+09
279913    1927     6975     4.5  1.36744e+09
279925    1927    27773     5.0  1.30205e+09
279930    1927    33166     4.5  1.30217e+09
279934    1927    44191     4.5  1.30217e+09
279936    1927    48394     5.0  1.30205e+09
279945    1927    55442     4.5  1.30205e+09
279968    1927    70286     4.5  1.36571e+09
279974    1927    71899     4.5  1.30373e+09
279978    1927    74458     4.5  1.36839e+09
279980    1927    77307     4.5  1.30195e+09
279982    1927    77658     5.0  1.36597e+09
279984    1927    79008     5.0  1.30203e+09
279992    1927    84273     4.5  1.30205e+09
279997    1927    89759     4.5  1.32692e+09
280000    1928       10     5.0  8.29399e+08
280001    1928       14     5.0  8.29399e+08
280004    1928       21     5.0  8.29399e+08
280007    1928       25     5.0  8.29399e+08
280009    1928       32     5.0  8.29399e+08
280011    1928       36     5.0  8.29399e+08

[60780 rows x 4 columns]

In [124]:
#Find how many null values, missing values are present. Deal with them. Print out how many rows have been modified.
null_columns=dfRatings.columns[dfRatings.isnull().any()]
null_columns.fillna("No Timestamp")
#print(dfRatings)
rws=dfRatings[dfRatings['timestamp']=="No Timestamp"]
print('No:of rows=',rws.shape[0])

No:of rows= 1

In [36]:
#Filter out movies from the movies DataFrame that are of type 'Animation'.
dfMovies[dfMovies.genres.str.contains("Animation")]

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
12,13,Balto (1995),Adventure|Animation|Children
47,48,Pocahontas (1995),Animation|Children|Drama|Musical|Romance
236,239,"Goofy Movie, A (1995)",Animation|Children|Comedy|Romance
241,244,Gumby: The Movie (1995),Animation|Children
310,313,"Swan Princess, The (1994)",Animation|Children
360,364,"Lion King, The (1994)",Adventure|Animation|Children|Drama|Musical|IMAX
388,392,"Secret Adventures of Tom Thumb, The (1993)",Adventure|Animation
547,551,"Nightmare Before Christmas, The (1993)",Animation|Children|Fantasy|Musical
553,558,"Pagemaster, The (1994)",Action|Adventure|Animation|Children|Fantasy
582,588,Aladdin (1992),Adventure|Animation|Children|Comedy|Musical
588,594,Snow White and the Seven Dwarfs (1937),Animation|Children|Drama|Fantasy|Musical
589,595,Beauty and the Beast (1991),Animation|Children|Fantasy|Musical|Romance|IMAX
590,596,Pinocchio (1940),Animation|Children|Fantasy|Musical
604,610,Heavy Metal (1981),Action|Adventure|Animation|Horror|Sci-Fi
610,616,"Aristocats, The (1970)",Animation|Children
624,631,All Dogs Go to Heaven 2 (1996),Adventure|Animation|Children|Fantasy|Musical|R...
653,661,James and the Giant Peach (1996),Adventure|Animation|Children|Fantasy|Musical
664,673,Space Jam (1996),Adventure|Animation|Children|Comedy|Fantasy|Sc...
697,709,Oliver & Company (1988),Adventure|Animation|Children|Comedy|Musical
708,720,Wallace & Gromit: The Best of Aardman Animatio...,Adventure|Animation|Comedy
728,741,Ghost in the Shell (Kôkaku kidôtai) (1995),Animation|Sci-Fi
732,745,Wallace & Gromit: A Close Shave (1995),Animation|Children|Comedy
770,783,"Hunchback of Notre Dame, The (1996)",Animation|Children|Drama|Musical|Romance
871,888,Land Before Time III: The Time of the Great Gi...,Adventure|Animation|Children|Musical
1003,1022,Cinderella (1950),Animation|Children|Fantasy|Musical|Romance
1004,1023,Winnie the Pooh and the Blustery Day (1968),Animation|Children|Musical
1005,1024,"Three Caballeros, The (1945)",Animation|Children|Musical
1006,1025,"Sword in the Stone, The (1963)",Animation|Children|Fantasy|Musical
1010,1029,Dumbo (1941),Animation|Children|Drama|Musical
...,...,...,...
27007,129830,Animals United (2011),Animation|Children|Comedy
27008,129834,Tom and Jerry: The Lost Dragon (2014),Animation|Children|Comedy
27018,129859,Mardock Scramble: The Second Combustion (2011),Animation|Sci-Fi
27054,130034,Stand by Me Doraemon (2014),Animation|Children|Drama|Fantasy
27070,130075,Frozen Fever (2015),Adventure|Animation
27103,130394,The Mascot (1934),Animation
27107,130402,Cardcaptor Sakura: The Sealed Card (2000),Adventure|Animation|Comedy|Fantasy|Romance
27129,130506,Berserk: The Golden Age Arc 2 - The Battle for...,Action|Animation|Fantasy
27130,130508,Berserk: The Golden Age Arc - The Egg of the K...,Action|Adventure|Animation|Fantasy|Horror
27131,130510,Berserk: The Golden Age Arc 3 - Descent (2013),Action|Animation|Fantasy
27135,130518,The Amazing Screw-On Head (2006),Action|Adventure|Animation|Comedy|Sci-Fi
27136,130520,Home (2015),Animation|Children|Comedy|Fantasy|Sci-Fi
27137,130522,The Brave Little Toaster Goes to Mars (1998),Animation|Children
27155,130644,The Garden of Sinners - Chapter 5: Paradox Par...,Animation
27205,131058,Santa's Apprentice (2010),Animation|Children
27208,131066,Ronal the Barbarian (2011),Adventure|Animation|Fantasy
27215,131080,Cinderella III: A Twist in Time (2007),Animation|Children|Fantasy|Romance
27218,131086,The Little Polar Bear: Lars and the Little Tig...,Animation|Children
27221,131092,"Mickey, Donald, Goofy: The Three Musketeers (2...",Adventure|Animation|Children|Comedy
27222,131094,Rudolph the Red-Nosed Reindeer: The Movie (1998),Animation|Children
27224,131098,Saving Santa (2013),Animation|Children|Comedy
27226,131102,Lucky Luke: The Ballad of the Daltons (1978),Animation|Children|Comedy|Western
27228,131106,Casper's Haunted Christmas (2000),Animation|Children
27235,131120,Superstar Goofy (1991),Animation|Children|Comedy
27240,131130,Tom and Jerry: A Nutcracker Tale (2007),Animation|Comedy
27241,131132,Kleines Arschloch - Der Film (1997),Animation|Comedy
27247,131144,Werner - Das muss kesseln!!! (1996),Animation|Comedy
27248,131146,Werner - Volles Rooäää (1999),Animation|Comedy
27269,131243,Werner - Gekotzt wird später (2003),Animation|Comedy
27270,131248,Brother Bear 2 (2006),Adventure|Animation|Children|Comedy|Fantasy

In [39]:
#Find the average rating of movies.
dfMean=dfRatings.groupby(['movieId'])["rating"].mean().reset_index(name ='Average_Rating')
dfMean

       movieId  Average_Rating
0            1        3.979046
1            2        3.250814
2            3        3.146893
3            4        3.033333
4            5        3.132124
5            6        3.889728
6            7        3.430108
7            8        3.173913
8            9        3.061538
9           10        3.436636
10          11        3.781250
11          12        2.707547
12          13        3.075000
13          14        3.483146
14          15        2.558824
15          16        3.796226
16          17        3.977966
17          18        3.409722
18          19        2.611486
19          20        2.950000
20          21        3.646628
21          22        3.251462
22          23        3.109375
23          24        3.254032
24          25        3.697842
25          26        3.635135
26          27        3.100000
27          28        4.073171
28          29        3.917355
29          30        3.615385
...        ...             ...
10831   118997        3.500000
10832   119141        3.333333
10833   119145        3.000000
10834   119167        2.000000
10835   119687        4.500000
10836   120392        4.000000
10837   120635        2.500000
10838   120811        1.000000
10839   120813        0.500000
10840   120815        1.000000
10841   120821        0.500000
10842   120823        4.000000
10843   120825        3.000000
10844   121117        3.500000
10845   121135        3.500000
10846   121583        4.000000
10847   122230        2.500000
10848   123639        3.000000
10849   124077        4.000000
10850   125916        0.500000
10851   126405        3.000000
10852   126426        4.000000
10853   127088        4.000000
10854   128488        3.000000
10855   128594        0.500000
10856   128686        3.000000
10857   128715        4.000000
10858   128832        4.500000
10859   128842        3.000000
10860   130219        4.500000

[10861 rows x 2 columns]

In [40]:
#Perform an inner join of movies and tags based on movieId.
pd.merge(dfMovies, dfTags, how='inner', on="movieId")

,movieId,title,genres,userId,tag,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1644,Watched,1417736680
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1741,computer animation,1183903155
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1741,Disney animated feature,1183933307
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1741,Pixar animation,1183934770
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1741,TÃ©a Leoni does not star in this movie,1245093573
5,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,2299,Pixar,1403306852
6,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3596,animation,1290312028
7,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3596,family,1290312032
8,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3596,Tom Hanks,1290312036
9,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,6233,Pixar,1387079572
10,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,6233,witty,1387079576
11,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,8219,Pixar,1159534063
12,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,adventure,1277357423
13,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,animated,1277357419
14,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,animation,1277357417
15,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,clever,1277357438
16,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,comedy,1277357433
17,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,computer animation,1277357405
18,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,family,1277357449
19,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,fantasy,1277357430
20,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,Tom Hanks,1277357411
21,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,bright,1173304070
22,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,DARING RESCUES,1173304095
23,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,fanciful,1173304058
24,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,HEROIC MISSION,1173304102
25,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,humorous,1173304049
26,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,light,1173304062
27,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,rousing,1173304074
28,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,TOYS COME TO LIFE,1173304091
29,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,UNLIKELY FRIENDSHIPS,1173304106
...,...,...,...,...,...,...
465534,131015,Hellgate (2011),Horror|Thriller,25978,Cary Elwes,1427585540
465535,131015,Hellgate (2011),Horror|Thriller,25978,Demons,1427585566
465536,131015,Hellgate (2011),Horror|Thriller,25978,Exorcism,1427585551
465537,131015,Hellgate (2011),Horror|Thriller,25978,Ghosts,1427585546
465538,131015,Hellgate (2011),Horror|Thriller,25978,Monks,1427585560
465539,131015,Hellgate (2011),Horror|Thriller,25978,nurse,1427585621
465540,131015,Hellgate (2011),Horror|Thriller,25978,psychic,1427585613
465541,131015,Hellgate (2011),Horror|Thriller,25978,slow,1427585575
465542,131015,Hellgate (2011),Horror|Thriller,25978,special effects,1427585690
465543,131015,Hellgate (2011),Horror|Thriller,25978,surfing,1427585592
465544,131015,Hellgate (2011),Horror|Thriller,25978,Thailand,1427585543
465545,131015,Hellgate (2011),Horror|Thriller,25978,William Hurt,1427585696
465546,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,Barcelona,1427641562
465547,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,exploitation,1427641559
465548,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,female football,1427641577
465549,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,football,1427641548
465550,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,Rome,1427641564
465551,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,shorts,1427641571
465552,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,soccer,1427641556
465553,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,transvestite,1427641589
465554,131054,Dinotopia: Quest for the Ruby Sunstone (2005),Children|Fantasy|Sci-Fi,88144,dinosaurs,1427654430
465555,131082,Playground (2009),(no genres listed),92885,documentary,1427654757
465556,131082,Playground (2009),(no genres listed),92885,Yoshitomo Nara,1427654856
465557,131164,Vietnam in HD (2011),War,54560,Vietnam War,1427667401
465558,131170,Parallels (2015),Sci-Fi,88738,alternate reality,1427732804
465559,131258,The Pirates (2014),Adventure,28906,bandits,1427745421
465560,131258,The Pirates (2014),Adventure,28906,Korea,1427745512
465561,131258,The Pirates (2014),Adventure,28906,mutiny,1427745542
465562,131258,The Pirates (2014),Adventure,28906,pirates,1427745419
465563,131258,The Pirates (2014),Adventure,28906,whale,1427745432

In [ ]:
#Print out the 5 movies that belong to the Comedy genre and have rating greater than 4.

In [55]:
dfComedy = dfMovies[dfMovies.genres.str.contains("Comedy")]
dfComedy=pd.merge(dfMovies[dfMovies.genres.str.contains("Comedy")],dfRatings[dfRatings.rating>4],how='inner',on=['movieId','movieId'])
dfComedy=dfComedy.groupby(["title"])["rating"].sum()
print(dfComedy.head(5))

title
'burbs, The (1989)                    18.5
(500) Days of Summer (2009)          109.0
*batteries not included (1987)        14.0
...And God Spoke (1993)                5.0
10 Things I Hate About You (1999)     70.5
Name: rating, dtype: float64

In [64]:
#Split 'genres' into multiple columns.
dfSplitCols = dfMovies['genres'].str.split('|', 5, expand=True)
print(dfSplitCols)

                        0          1         2        3         4     5
0               Adventure  Animation  Children   Comedy   Fantasy  None
1               Adventure   Children   Fantasy     None      None  None
2                  Comedy    Romance      None     None      None  None
3                  Comedy      Drama   Romance     None      None  None
4                  Comedy       None      None     None      None  None
5                  Action      Crime  Thriller     None      None  None
6                  Comedy    Romance      None     None      None  None
7               Adventure   Children      None     None      None  None
8                  Action       None      None     None      None  None
9                  Action  Adventure  Thriller     None      None  None
10                 Comedy      Drama   Romance     None      None  None
11                 Comedy     Horror      None     None      None  None
12              Adventure  Animation  Children     None      None  None
13                  Drama       None      None     None      None  None
14                 Action  Adventure   Romance     None      None  None
15                  Crime      Drama      None     None      None  None
16                  Drama    Romance      None     None      None  None
17                 Comedy       None      None     None      None  None
18                 Comedy       None      None     None      None  None
19                 Action     Comedy     Crime    Drama  Thriller  None
20                 Comedy      Crime  Thriller     None      None  None
21                  Crime      Drama    Horror  Mystery  Thriller  None
22                 Action      Crime  Thriller     None      None  None
23                  Drama     Sci-Fi      None     None      None  None
24                  Drama    Romance      None     None      None  None
25                  Drama       None      None     None      None  None
26               Children      Drama      None     None      None  None
27                  Drama    Romance      None     None      None  None
28              Adventure      Drama   Fantasy  Mystery    Sci-Fi  None
29                  Crime      Drama      None     None      None  None
...                   ...        ...       ...      ...       ...   ...
27248           Animation     Comedy      None     None      None  None
27249              Comedy    Romance      None     None      None  None
27250              Comedy       None      None     None      None  None
27251              Comedy       None      None     None      None  None
27252              Comedy       None      None     None      None  None
27253              Comedy       None      None     None      None  None
27254              Comedy       None      None     None      None  None
27255               Drama       None      None     None      None  None
27256               Drama    Romance      None     None      None  None
27257                 War       None      None     None      None  None
27258  (no genres listed)       None      None     None      None  None
27259               Drama       None      None     None      None  None
27260              Sci-Fi       None      None     None      None  None
27261  (no genres listed)       None      None     None      None  None
27262               Drama    Romance  Thriller     None      None  None
27263               Drama       None      None     None      None  None
27264              Action     Horror  Thriller     None      None  None
27265              Comedy    Romance      None     None      None  None
27266              Comedy       None      None     None      None  None
27267              Comedy      Drama      None     None      None  None
27268              Comedy    Romance      None     None      None  None
27269           Animation     Comedy      None     None      None  None
27270           Adventure  Animation  Children   Comedy   Fantasy  None
27271              Comedy       None      None     None      None  None
27272              Comedy     Horror      None     None      None  None
27273              Comedy       None      None     None      None  None
27274              Comedy       None      None     None      None  None
27275           Adventure       None      None     None      None  None
27276  (no genres listed)       None      None     None      None  None
27277           Adventure    Fantasy    Horror     None      None  None

[27278 rows x 6 columns]

In [77]:
#Extract year from title e.g. (1995).
dfYr = dfMovies["title"].str.extract(r'(\d{4})')
print(dfYr)

          0
0      1995
1      1995
2      1995
3      1995
4      1995
5      1995
6      1995
7      1995
8      1995
9      1995
10     1995
11     1995
12     1995
13     1995
14     1995
15     1995
16     1995
17     1995
18     1995
19     1995
20     1995
21     1995
22     1995
23     1995
24     1995
25     1995
26     1995
27     1995
28     1995
29     1995
...     ...
27248  1999
27249  2011
27250  2006
27251  1966
27252  1999
27253  2002
27254  1991
27255  2009
27256  2014
27257  2011
27258  2009
27259  2014
27260  2015
27261  2013
27262  2014
27263  2014
27264  2015
27265  2014
27266  2010
27267  2011
27268  2000
27269  2003
27270  2006
27271  2000
27272  2001
27273  2007
27274  2002
27275  2014
27276  2001
27277  2014

[27278 rows x 1 columns]

In [94]:
#Get timestamp for 2015-02-01.
import time
ts=time.mktime(time.strptime('2015-02-01', "%Y-%m-%d"))

#Select rows based on timestamps later than 2015-02-01.
dft=dfRatings[dfRatings['timestamp']>ts]
print(dft)

        userId  movieId  rating     timestamp
3534        31        1     3.0  1.424733e+09
3535        31      110     5.0  1.424733e+09
3536        31      260     5.0  1.424733e+09
3537        31      364     3.0  1.424845e+09
3538        31      527     0.5  1.424734e+09
3539        31      588     3.0  1.424843e+09
3540        31      594     2.5  1.424845e+09
3541        31      616     4.0  1.424845e+09
3542        31     1196     5.0  1.424733e+09
3543        31     1197     3.0  1.424734e+09
3544        31     1207     0.5  1.424734e+09
3545        31     1210     5.0  1.424733e+09
3546        31     1214     0.5  1.424734e+09
3547        31     1270     4.0  1.424733e+09
3548        31     2096     2.0  1.424845e+09
3549        31     2571     4.5  1.424737e+09
3550        31     2959     2.0  1.424734e+09
3551        31     3300     5.0  1.424734e+09
3552        31     3483     4.0  1.424736e+09
3553        31     3555     3.0  1.424734e+09
3554        31     3615     3.0  1.424734e+09
3555        31     3624     3.0  1.424734e+09
3556        31     3671     5.0  1.424734e+09
3557        31     3751     4.0  1.424737e+09
3558        31     3793     4.5  1.424734e+09
3559        31     3916     4.5  1.424735e+09
3560        31     4016     4.0  1.424734e+09
3561        31     4022     2.0  1.424735e+09
3562        31     4232     4.0  1.424734e+09
3563        31     4299     3.0  1.424734e+09
...        ...      ...     ...           ...
249934    1734     3176     4.0  1.424280e+09
249935    1734     3362     4.0  1.426288e+09
249954    1734     5147     4.0  1.422914e+09
249956    1734     5867     4.0  1.424994e+09
249970    1734     7076     4.0  1.423531e+09
249989    1734    41285     4.0  1.424280e+09
249991    1734    44555     4.5  1.425421e+09
249999    1734    54259     3.5  1.423506e+09
250003    1734    55820     4.0  1.423507e+09
250023    1734    80489     4.0  1.423531e+09
250044    1734    96811     4.0  1.423531e+09
250052    1734   101285     3.5  1.426384e+09
250060    1734   103980     4.0  1.425619e+09
250061    1734   103984     4.5  1.427395e+09
250077    1734   110553     3.0  1.427130e+09
250081    1734   111661     4.0  1.423088e+09
250088    1734   113705     4.0  1.425847e+09
250090    1734   114935     4.0  1.423094e+09
250092    1734   116138     4.0  1.427395e+09
250096    1734   118700     4.0  1.424572e+09
250097    1734   118898     4.0  1.426793e+09
250806    1741      903     4.0  1.426975e+09
251077    1741     2926     3.0  1.427151e+09
251087    1741     2971     4.5  1.426976e+09
251337    1741     6564     2.0  1.427151e+09
251551    1741    52435     3.5  1.426976e+09
251678    1741    95858     3.5  1.426975e+09
251700    1741   117851     2.5  1.427238e+09
267426    1848    65261     4.0  1.422765e+09
267432    1848    81845     4.0  1.422765e+09

[3271 rows x 4 columns]

In [99]:
#Sort the tags DataFrame based on timestamp.
dfTags.sort_values(by=['timestamp'])

        userId  movieId                              tag   timestamp
333932  100371     2788                     monty python  1135429210
333927  100371     1732                    coen brothers  1135429236
333924  100371     1206                  stanley kubrick  1135429248
333923  100371     1193                   jack nicholson  1135429371
333939  100371     5004                    peter sellers  1135429399
333922  100371       47                   morgan freeman  1135429412
333921  100371       47                        brad pitt  1135429412
333936  100371     4011                        brad pitt  1135429431
333937  100371     4011                      guy ritchie  1135429431
333920  100371       32                     bruce willis  1135429442
333933  100371     2858                     kevin spacey  1135429466
333931  100371     2329                     fuckoff nazi  1135429508
333930  100371     2329                    edward norton  1135429508
333944  100371     6016                           brazil  1135429520
15903     3797      110                        overrated  1135589075
256663   75141     4642                         Terrible  1135688095
15926     3797     8573             Nonlinear Surrealism  1135936223
68928    16050    38886                             twee  1136036612
68924    16050    38886                         eighties  1136036612
68925    16050    38886                           family  1136036612
68926    16050    38886                         new york  1136036612
68927    16050    38886                        overrated  1136036612
68919    16050     7060                        christian  1136039301
68921    16050     7060                          musical  1136039301
68920    16050     7060                           kitsch  1136039301
68922    16050     7060                        religious  1136039301
68918    16050     6898                            harsh  1136039368
68916    16050     6898                          british  1136039368
68917    16050     6898                            drugs  1136039368
81444    20513    36529                            truth  1136242623
...        ...      ...                              ...         ...
119997   28906   115149                          violent  1427746031
119991   28906   115149                    lack of story  1427746053
119993   28906   115149                     over the top  1427746060
119989   28906   115149                           cheesy  1427746074
405155  123297   128642                              CLV  1427746337
399877  123297     4211                              CLV  1427746709
400993  123297     6419                              CLV  1427746864
401017  123297     6481                              CLV  1427747220
405123  123297   118722                              CLV  1427747321
400106  123297     4573                              CLV  1427747462
150873   42640   115122                     mockumentary  1427748778
150871   42640   115122                           comedy  1427748797
150872   42640   115122                      dark comedy  1427748808
392905  122523     5004                              USA  1427752289
392904  122523     5004                            party  1427752292
290536   88044   106782              unsatisfying ending  1427753000
290534   88044   106782                           Orgies  1427753111
290529   88044   106782                             ENFP  1427753147
290532   88044   106782             Left-Wing Propaganda  1427753266
290533   88044   106782                Left-Wing Writers  1427753621
290528   88044   106782  Economically Illiterate Writers  1427753739
290530   88044   106782                       inaccurate  1427753806
290531   88044   106782                       Jonah Hill  1427753849
290526   88044   106782                           Amoral  1427753913
290527   88044   106782                            crime  1427753921
290535   88044   106782                        profanity  1427754096
288375   87797      215                           Vienna  1427755801
158763   46072     3409                      premonition  1427760726
158780   46072     6058                      premonition  1427760764
339178  102853   115149                    russian mafia  1427771352

[465564 rows x 4 columns]